version: '3.5'
services:
  sa_mysql:
    image: 'mysql:latest'
    container_name: sa_mysql
    restart: always
    networks:
      net:
        ipv4_address: ${MYSQL_HOST}
    volumes:
      - './mysql/initdb/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql'
      - ${DATA_PATH_HOST}/mysql/:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306

  sa_nginx:
    build: ./nginx
    container_name: sa_nginx
    restart: always
    networks:
      net:
        ipv4_address: ${NGINX_HOST}
    links:
      - sa_mysql
      - sa_php
      - sa_redis
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/
      - ./../api/:/var/www/api/
      - ./../mock/:/var/www/mock/

  sa_php:
    build:
      context: ./php
    tty: true
    container_name: sa_php
    restart: always
    links:
      - sa_mysql
      - sa_redis
      - sa_rabbitmq
    depends_on:
      - sa_mysql
      - sa_redis
      - sa_rabbitmq
    expose:
      - 9000
    volumes:
      - ./../api/:/var/www/api/
      - ./../mock/:/var/www/mock/
      - ./php/supervisor_conf/api.conf:/etc/supervisor/conf.d/api.conf
      - ./php/supervisor_conf/supervisord.conf:/etc/supervisord.conf
      - ./php/crontab:/etc/cron.d
    extra_hosts:
      - "mockapi.net:172.17.0.1"
    networks:
      net:

  sa_redis:
    container_name: sa_redis
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      net:

  sa_rabbitmq:
    container_name: sa_rabbitmq
    build:
      context: ./rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    environment:
      - RABBITMQ_LOG_BASE=${RABBITMQ_LOG_BASE}
      - RABBITMQ_ERLANG_COOKIE=${RABITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAUL_VHOST}
    networks:
      net:

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
